TestWebWPF_v1/Controllers/MangaController.cs
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Net.Http;
using System.Security.Policy;
using System.Text.RegularExpressions;
using TestWebWPF_v1.Models;
using TestWebWPF_v1.Models.View;

namespace TestWebWPF_v1.Controllers
{
    public class MangaController : Controller
    {
        private static HttpClient hc = new HttpClient();
        private static string strUrl = @"https://localhost:7132/Truyen-tranh"; //https://content.yahallo.online/Truyen-tranh, https://localhost:7132/Truyen-tranh, https://yahallomanga.azurewebsites.net/Truyen-tranh
        private List<BoTruyen> _dsBotruyen;
        private List<ChuongTruyen> _dsChuongtruyen;
        public MangaController()
        {
            _dsBotruyen = getDSBoTruyen();
            _dsChuongtruyen = getDsChapter();
        }
        // Lấy danh sách truyện
        public IActionResult Index()
        {
            return View(_dsBotruyen);
        }

        /*--------------------------------------------------------Begin Action Manga-------------------------------------------*/

        //Chi tiết bộ truyện cụ thể
        [Route("Details/{Id}")]
        public IActionResult formChitietTruyen(string Id,bool success)
        {
            BoTruyen? a = (_dsBotruyen.FirstOrDefault(x => x.MangaId == Id) != null) ? _dsBotruyen.FirstOrDefault(x => x.MangaId == Id) : null;
            if (a != null)
            {
                if (success) ViewBag.request = "Thành công";
                return View(a);
            }
            else
            {
                return Content("<script language='javascript' type='text/javascript'>alert('Save Successfully');</script>");
            } 
        }

        //Form tạo bộ truyện
        [Route("CreateManga")]
        public IActionResult formThemManga()
        {
            return View();
        }
        //Action tạo bộ truyện
        [Route("ActionCreateManga")]
        public IActionResult CreateManga(string MangaName, string MangaDetails, IFormFile? MangaImage, string MangaAlternateName
            , string MangaAuthor, string MangaArtist, string MangaGenre)
        {
            try
            {
                List<string> ds = _dsBotruyen.Select(x => x.MangaId).ToList();// phải lấy tất cả bộ truyện sau đó mới dùng được
                string Id = ranDomId(ds);

                var formData = new MultipartFormDataContent();
                formData.Add(new StringContent(Id), "MangaId");
                formData.Add(new StringContent(MangaName), "MangaName");
                formData.Add(new StringContent(MangaDetails), "MangaDetails");
                if (MangaImage != null) formData.Add(new StreamContent(MangaImage.OpenReadStream()), "MangaImage", MangaImage.FileName);
                formData.Add(new StringContent(MangaAlternateName), "MangaAlternateName");
                formData.Add(new StringContent(MangaAuthor), "MangaAuthor");
                formData.Add(new StringContent(MangaArtist), "MangaArtist");
                formData.Add(new StringContent(MangaGenre), "MangaGenre");
                string url = strUrl + @"/Create";
                var response = hc.PostAsync(url, formData);
                response.Wait();
                if (response.Result.IsSuccessStatusCode)
                    return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return ViewBag.request("Không thể thêm truyện");
            }
            return ViewBag.request("Không thể thêm truyện");
        }

        //Form sửa thông tin bộ truyện
        [Route("EditManga-{Id}")]
        public IActionResult formSuaTruyen(string Id)
        {
            BoTruyen? a = _dsBotruyen.FirstOrDefault(x => x.MangaId == Id);
            return View(a);
        }
        //Hàm sửa thông tin của bộ truyện
        [Route("ActionEditManga")]
        public IActionResult SuaTruyen(string MangaId, string? MangaName, string? MangaDetails, IFormFile? MangaImage, string? MangaAlternateName
            , string? MangaAuthor, string? MangaArtist, string? MangaGenre)
        {
            try
            {
                var formData = new MultipartFormDataContent();
                formData.Add(new StringContent(MangaId), "MangaId");
                if (MangaName != null) formData.Add(new StringContent(MangaName), "MangaName");
                if (MangaDetails != null) formData.Add(new StringContent(MangaDetails), "MangaDetails");
                if (MangaImage != null) formData.Add(new StreamContent(MangaImage.OpenReadStream()), "MangaImage", MangaImage.FileName);
                if (MangaAlternateName != null) formData.Add(new StringContent(MangaAlternateName), "MangaAlternateName");
                if (MangaAuthor != null) formData.Add(new StringContent(MangaAuthor), "MangaAuthor");
                if (MangaArtist != null) formData.Add(new StringContent(MangaArtist), "MangaArtist");
                if (MangaGenre != null) formData.Add(new StringContent(MangaGenre), "MangaGenre");
                string url = strUrl + @"/EditManga/" + MangaId;
                var response = hc.PutAsync(url, formData);
                response.Wait();
                if (response.Result.IsSuccessStatusCode)
                    return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return ViewBag.request("Không thể thêm truyện");
            }
            return ViewBag.request("Không thể thêm truyện");
        }

        [HttpPost]
        [Route("DeleteManga-{MangaId}")]
        public IActionResult xoaTruyen(string MangaId)
        {
            try
            {
                string url = strUrl + @"/Delete/" + MangaId;
                var response = hc.DeleteAsync(url);
                response.Wait();
                if (response.Result.IsSuccessStatusCode)
                    return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return ViewBag.request("Không thể thêm truyện");
            }
            return ViewBag.request("Không thể thêm truyện");
        }
        /*-------------------------------------------------------End Action Manga------------------------------------------------*/
        /*--------------------------------------------------------Begin Action Chapter-------------------------------------------*/

        //Form tạo chương truyện
        [Route("{Id}/CreateChapter")]
        public IActionResult formcreateChapter(string Id)
        {
            ViewBag.MangaId = Id;
            return View();
        }

        //Action tạo chương truyện
        [Route("ActionCreateChapter")]
        public  IActionResult CreateChapter(
            string MangaId, string TieuDe, string tenChuong, List<IFormFile>? file, string? dsurl)
        {
            try
            {
                List<string> ds = _dsChuongtruyen.Select(x=>x.ChapterId).ToList(); //phải tạo hàm để lấy tất cả chương truyện sao đó mới dùng được
                string Id = "c" + ranDomId(ds);

                var formdata = new MultipartFormDataContent();
                if (file != null)
                {
                    foreach (var xfile in file)
                    {
                        formdata.Add(new StreamContent(xfile.OpenReadStream()), "MangaImage", xfile.FileName);
                    }
                }
                if (dsurl != null)
                {
                    //List<string> dsa=await checkUrlImage(dsurl);
                    List<string> dsa = dsurl.Split(new[] { "https", "http" }, StringSplitOptions.RemoveEmptyEntries).ToList();
                    foreach (string x in dsa)
                    {
                        formdata.Add(new StringContent(x), "MangaUrl");
                    }

                }
                formdata.Add(new StringContent(Id), "ChapterId");
                formdata.Add(new StringContent(tenChuong), "tenChuong");
                formdata.Add(new StringContent(TieuDe), "TieuDe");
                formdata.Add(new StringContent(MangaId), "MangaId");
                string httpurl = strUrl + @"/{MangaId}/CreateChapter";
                var response = hc.PostAsync(httpurl, formdata);
                response.Wait();
                if (response.Result.IsSuccessStatusCode)
                return RedirectToAction("formChitietTruyen", new { Id = MangaId, success = true });
            }
            catch (Exception)
            {
                return ViewBag.result="<div class='alert-danger'>Thêm thất bại</div>";
            }
            return Ok();
        }

        //Form Sửa chương truyện
        [Route("{IdManga}/{ChapterId}/EditChapter")]
        public IActionResult formEditChapter(string idManga, string ChapterId)
        {
            ViewBag.MangaId = idManga;
            var chapter = _dsChuongtruyen.FirstOrDefault(x => x.ChapterId == ChapterId);
            return View(chapter);
        }

        //Action Sửa chương truyện
        [Route("ActionEditChapter")]
        public IActionResult EditChapter(
            string MangaId,string maChuong, string TieuDe, string tenChuong, List<IFormFile>? file, string? dsurl)
        {
            try
            {
                var formdata = new MultipartFormDataContent();
                if (file != null)
                {
                    foreach (var xfile in file)
                    {
                        formdata.Add(new StreamContent(xfile.OpenReadStream()), "MangaImage", xfile.FileName);
                    }
                }
                if (dsurl != null)
                {
                    List<string> dsa = dsurl.Split(new[] { "https", "http" }, StringSplitOptions.RemoveEmptyEntries).ToList();
                    foreach (string x in dsa)
                    {
                        formdata.Add(new StringContent(x), "MangaUrl");
                    }

                }

TestWebWPF_v1/Views/Manga/Index.cshtml
@model IEnumerable<TestWebWPF_v1.Models.BoTruyen>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="formThemManga" class="btn btn-primary" >Thêm truyện</a>
</p>
<table id="myTable" class="table">
    <thead>
        <tr>
            <th>
                Mã truyện
            </th>
            <th>
                Tên truyện
            </th>
            <th>
                Ghi chú
            </th>
            <th>
                Tên khác
            </th>
            <th>
                Tác giả
            </th>
            <th>
                Họa sĩ
            </th>
            <th>
               Loại truyện
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
            <tr id="Chapter_@item.MangaId">
            <td>
                @Html.DisplayFor(modelItem => item.MangaId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MangaName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MangaDetails)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MangaAlternateName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MangaAuthor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MangaArtist)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MangaGenre)
            </td>
            <td>
                <a href="@Url.Action("formChitietTruyen","Manga",new { Id=item.MangaId,success=false})" class="btn btn-primary">Chi tiết</a>
                <br/>
                <a href="@Url.Action("formSuaTruyen","Manga",new { Id=item.MangaId})" class="btn btn-primary">Sửa truyện</a>
                <br />
                <button type="submit" onclick="return confirmDelete('@item.MangaId')" class="btn btn-primary">Xóa Tuyện</button>
            </td>
        </tr>
}
    </tbody>
</table>
@section Manga{
    <script>
        // Kiểm tra xem trang có query string "success" không
        var urlParams = new URLSearchParams(window.location.search);
        var successParam = urlParams.get('success');

        // Nếu có query string "success" và giá trị là "true", hiển thị thông báo
        if (successParam === 'true') {
            alert("Thành công");
        }
        function confirmDelete(MangaId) {
            var result = confirm("Bạn có chắc chắn muốn xóa truyện này?");
            if (result) {
                delete_Click(MangaId);
            }
            return result;
        }
        function delete_Click(MangaId) {
            var xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    alert("Đã xóa thành công!");
                    var trElement = document.getElementById('Chapter_' + MangaId);// if only one id
                    if (trElement) {
                        trElement.remove();
                    }
                }
            };
            var strUrl = "/DeleteManga-"+MangaId;
            xhttp.open("POST", strUrl, true);
            xhttp.send();
        }
    </script>
}

TestWebWPF_v1/Views/Manga/formChitietTruyen.cshtml
@model TestWebWPF_v1.Models.BoTruyen

@{
    ViewData["Title"] = "formChitietTruyen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Chi tiết truyện</h1>
@{
    if (ViewBag.request != null){
        <div class="alert alert-success align-content-center">@ViewBag.request</div>}
}
<div>
    <h4>BoTruyen</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Id
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MangaId)
        </dd>
        <dt class = "col-sm-2">
            Tên truyện
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MangaName)
        </dd>
        <dt class = "col-sm-2">
            Nội dung
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MangaDetails)
        </dd>
        <dt class = "col-sm-2">
            Ảnh bìa
        </dt>
        <dd class = "col-sm-10">
            <img style="width:100px;height:100px;" src="@Model.MangaImage" class="img-thumbnail" alt="Ảnh" onerror="this.src='/image/error.gif'"/>
        </dd>
        <dt class = "col-sm-2">
            Tên khác
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MangaAlternateName)
        </dd>
        <dt class = "col-sm-2">
            Tác giả
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MangaAuthor)
        </dd>
        <dt class = "col-sm-2">
            Họa sĩ
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MangaArtist)
        </dd>
        <dt class = "col-sm-2">
            Loại truyện
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MangaGenre)
        </dd>
    </dl>
</div>
<div>
    <a href="@Url.Action("formcreateChapter","Manga",new { Id=Model.MangaId})" class="btn btn-primary">Thêm Chương</a>
    <br />
    <a href="@Url.Action("listChapter","Manga",new { Id=Model.MangaId})" class="btn btn-primary">Danh sách chương</a>
    <br />
    <a class="btn btn-primary" asp-action="Index">Quay lại</a>
</div>
@section Manga{
    <script>
        $(document).ready(function () {
            setTimeout(function () {
                $('.alert').hide();
            }, 3000);
        });
    </script>
}

TestWebWPF_v1/Views/Manga/formEditChapter.cshtml
@model TestWebWPF_v1.Models.ChuongTruyen

@{
    ViewData["Title"] = "formEditChapter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Sửa chương</h1>

<hr />
<p>
    <a href="@Url.Action("formChitietTruyen","Manga",new { Id=@ViewBag.MangaId,success=false})" class="btn btn-primary">Quay lại</a>
</p>

<div class="row">
    <div class="col-md-4">
        <form asp-action="EditChapter" enctype="multipart/form-data" method="post">
            <div class="row">
                <label class="control-label">Mã Chương</label>
                <input asp-for=ChapterId type="text" name="maChuong" class="form-control" readonly/>
                <span class="error-msg"></span>
            </div>
            <div class="row">
                <label class="control-label">Tên Chương</label>
                <input asp-for=ChapterName type="text" name="tenChuong" class="form-control" onblur="validateInput(this)" required />
                <span class="error-msg"></span>
            </div>
            <div class="row">
                <label class="control-label">Tiêu để chương</label>
                <input asp-for="ChapterTitle" type="text" name="TieuDe" class="form-control" onblur="validateInput(this)" required />
                <span class="error-msg"></span>
            </div>
            <div class="row">
                <label class="control-label">Url</label>
            </div>
            <div class="row">
                <textarea name="dsurl" rows="8" cols="50"></textarea>
            </div>
            <div class="row">
                <input type="file" name="file" multiple />
                <input type="text" name="MangaId" value="@ViewBag.MangaId" hidden="hidden" />
            </div>
            <div class="row">
                <p>
                    <input id="submit" type="submit" value="Sửa" class="btn btn-primary" />
                </p>
            </div>
        </form>
    </div>
</div>
@section Manga{
    <script>
        function validateInput(inputElement) {
            var inputValue = inputElement.value.trim();
            var errorElement = inputElement.nextElementSibling;

            if (inputValue === "") {
                errorElement.textContent = "Không được bỏ trống.";
                errorElement.classList.add("error-msg");
            } else {
                errorElement.textContent = "";
                errorElement.classList.remove("error-msg");
            }
        }
    </script>
}

TestWebWPF_v1/Views/Manga/formSuaTruyen.cshtml
@model TestWebWPF_v1.Models.BoTruyen
@{
    ViewData["Title"] = "formSuaTruyen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Sửa truyện</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SuaTruyen" enctype="multipart/form-data" method="post">

            <input asp-for="MangaId" class="form-control" name="MangaId" readonly />

            <label class="control-label">Tên truyện</label>
            <input asp-for="MangaName" type="text" name="MangaName" class="form-control" />

            <label class="control-label">Ghi chú</label>
            <input asp-for="MangaDetails" type="text" name="MangaDetails" class="form-control" />

            <label class="control-label">Ảnh bìa</label>
            <img src="@Model.MangaImage" alt="Img" onerror="this.src='/image/error.gif'" id="anhbia" class="img-thumbnail w-25 h-25"/>
            <input type="file" name="MangaImage" class="form-control" id="imgThumbnail"/>

            <label class="control-label">Tên khác</label>
            <input asp-for="MangaAlternateName" type="text" name="MangaAlternateName" class="form-control" />

            <label lass="control-label">Tác giả</label>
            <input asp-for="MangaAuthor" type="text" name="MangaAuthor" class="form-control" />

            <label class="control-label">Họa sĩ</label>
            <input asp-for="MangaArtist" type="text" name="MangaArtist" class="form-control" />

            <label class="control-label">Loại truyện</label>
            <select id="MangaGenre" name="MangaGenre">
                <option value="Oneshot">Oneshot</option>
                <option value="Series">Series</option>
            </select>   

            <br />
            <input type="submit" value="Sửa" class="btn btn-primary" />
        </form>
    </div>
</div>
@section EditManga{
    <script>
        $(document).ready(function () {
            var selectedValue = "@Model.MangaGenre";
            $("#MangaGenre").val(selectedValue);
        });
        $("#imgThumbnail").on("change", function () {
            var a = document.getElementById("anhbia");
            a.src = URL.createObjectURL(this.files[0]);
        })
    </script>
}

TestWebWPF_v1/Views/Manga/formThemManga.cshtml
@model TestWebWPF_v1.Models.BoTruyen

@{
    ViewData["Title"] = "formThemManga";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4>Thêm truyện</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateManga" enctype="multipart/form-data" method="post">
            <div class="row">
                <label class="control-label">Tên truyện</label>
                <input type="text" name="MangaName" class="form-control" onblur="validateInput(this)" required />
                <span class="error-msg"></span>
            </div>
            <div class="row">
                <label class="control-label">Ghi chú</label>
                <input type="text" name="MangaDetails" class="form-control" onblur="validateInput(this)" required />
                <span class="error-msg"></span>
            </div>
            <div class="row">
                <label class="control-label">Ảnh bìa</label>
                <input type="file" name="MangaImage" class="form-control" />
            </div>
            <div class="row">
                <label class="control-label">Tên khác</label>
                <input type="text" name="MangaAlternateName" class="form-control" onblur="validateInput(this)" required />
                <span class="error-msg"></span>
            </div>
            <div class="row">
                <label lass="control-label">Tác giả</label>
                <input type="text" name="MangaAuthor" class="form-control" onblur="validateInput(this)" required />
                <span class="error-msg"></span>
            </div>
            <div class="row">
                <label class="control-label">Họa sĩ</label>
                <input type="text" name="MangaArtist" class="form-control" onblur="validateInput(this)" required />
                <span class="error-msg"></span>
            </div>
            <div class="row">
            <label class="control-label">Loại truyện</label>
                <select name="MangaGenre">
                    <option value="Oneshot">Oneshot</option>
                    <option value="Series">Series</option>
                </select>
            </div>

            <div class="row" style="margin-top:10px;">
                <input type="submit" value="Thêm" class="btn btn-primary" />
            </div>
       </form>
    </div>
</div>
@section CreateManga{
    <script>
        function validateInput(inputElement) {
            var inputValue = inputElement.value.trim();
            var errorElement = inputElement.nextElementSibling;

            if (inputValue === "") {
                errorElement.textContent = "Vui lòng nhập thông tin.";
                errorElement.classList.add("error-msg");
            } else {
                errorElement.textContent = "";
                errorElement.classList.remove("error-msg");
            }
        }
    </script>
}

TestWebWPF_v1/Views/Manga/formcreateChapter.cshtml
@model TestWebWPF_v1.Models.ChuongTruyen

@{
    ViewData["Title"] = "createChapter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateChapter" enctype="multipart/form-data" method="post">
            <div class="row">
                <label class="control-label">Tên Chương</label>
                <input type="text" name="tenChuong" class="form-control" />
            </div>
            <div class="row">
                <label class="control-label">Tiêu để chương</label>
                <input type="text" name="TieuDe" class="form-control" />
            </div>
            <div class="row">
                <label class="control-label">Url</label>
            </div>
            <div class="row">
                <textarea name="url" rows="8" cols="50"></textarea>
            </div>
            <div class="row">
                <input type="file" name="file" multiple />
                <input type="text" name="MangaId" value="@ViewBag.MangaId" hidden="hidden" />
            </div>
            <div class="row">
                <p>
                    <input type="submit" value="Tạo" class="btn btn-primary" />
                </p>
            </div>
        </form>
    </div>
</div>

TestWebWPF_v1/Views/Manga/layAnhChuong.cshtml
<div class="container col-8 align-items-center justify-content-center">
    @{int x = 0;
        //<div class="row col-12 " style="display:block">
        //    <img id="Image" src="../wwwroot/image/loading.gif" class="img-thumbnail" alt="Ảnh" onerror="this.src='/image/error.gif'" loading="lazy" />
        //</div>
        @foreach (var a in ViewBag.DsImage)
        {
            while (x < ViewBag.DsImage.Count)
            {
                <div class="row col-12 " style="display:block">
                    <img id="@x" src="../wwwroot/image/loading.gif" class="img-thumbnail w-100 h-100" alt="Ảnh" onerror="this.src='/image/error.gif'" loading="lazy" />
                </div>
                x++;
            } 
        }
    }
</div>
@section DetailsChapter{
    <script>
        var imageIds = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(ViewBag.DsImage));
        async function createBlobUrlAsync(imageUrl) {
            const headers = {
                'Access-Control-Allow-Origin': '*'};
            return new Promise((resolve, reject) => {
                fetch(imageUrl, {
                    method: 'GET',
                    mode: 'cors',
                    responseType: 'blob',
                    headers
                })
                .then(response => response.blob())
                .then(blobData => {
                    resolve(blobData);
                })
                .catch(error => {
                    reject(error);
                });
            });
        }

        async function processImagesAsync() {
            var promises = imageIds.map(imageUrl => createBlobUrlAsync(imageUrl));
            try {
                //Xử lý và tạo blob cho từng image sau đó xuất chúng
                    for (var i = 0; i < imageIds.length; i++) {
                        const blobData = await createBlobUrlAsync(imageIds[i]);
                        const blobUrl = URL.createObjectURL(blobData);
                        var imgElement = document.getElementById(i);
                        imgElement.src = blobUrl;
                    }
                
                //Xử lý và tạo blob cho tất cả các image rồi mới xuất
                    //var blobs = await Promise.all(promises);

                    //for (var i = 0; i < blobs.length; i++) {
                    //    var blobData = blobs[i];
                    //    console.log("3 " + blobData);
                    //    var blobUrl = URL.createObjectURL(blobData);
                    //    console.log("4 " + blobUrl);
                    //    var imgElement = document.getElementById(i);
                    //    imgElement.src = blobUrl;
                    //}

                    //Chạy khá vui
                        //for (const imageUrl of imageIds) {
                        //    const blobData = await createBlobUrlAsync(imageUrl);
                        //    const blobUrl = URL.createObjectURL(blobData);
                        //    const imgElement = document.getElementById("Image");
                        //    imgElement.style.width="500px";
                        //    imgElement.style.height = "500px";
                        //    imgElement.src = blobUrl;

                        //    await new Promise(resolve => setTimeout(resolve, 100));
                        //}
                    
            } catch (error) {
                console.error('Lỗi khi tải dữ liệu Blob:', error);
            }
        }
        processImagesAsync();
    </script>
}

TestWebWPF_v1/Views/Manga/listChapter.cshtml
@model IEnumerable<TestWebWPF_v1.Models.View.chapterView>

@{
    ViewData["Title"] = "listChapter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>listChapter</h1>

<p>
    <a href="@Url.Action("formChitietTruyen","Manga",new { Id=@ViewBag.MangaId,success=false})" class="btn btn-primary">Quay lại</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Chapter_Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Chapter_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Chapter_Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Chapter_Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Manga_Id)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr id="Chapter_@item.Chapter_Id">
            <td>
                    @Html.DisplayFor(modelItem => item.Chapter_Id)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Chapter_Name)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Chapter_Title)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Chapter_Date)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Manga_Id)
            </td>
            <td>
                <a class="btn btn-primary" href="@Url.Action("layAnhChuong", "Manga", new {  idChapter=item.Chapter_Id,idManga=item.Manga_Id,listAnh=item.Imagechapter})">Chi tiết</a>
                    <a class="btn btn-primary" href="@Url.Action("formEditChapter", "Manga", new {  ChapterId=item.Chapter_Id,IdManga=item.Manga_Id})">Sửa</a>
                    <button type="submit" onclick="return confirmDeleteChapter('@item.Manga_Id','@item.Chapter_Id')" class="btn btn-primary">Xóa Chương</button>
            </td>
        </tr>
}
    </tbody>
</table>
@section Chapter{
    <script>
        function confirmDeleteChapter(MangaId,ChapterId) {
            var result = confirm("Bạn có chắc chắn muốn xóa chương truyện này?");
            if (result) {
                deleteChapter_Click(MangaId,ChapterId);
            }
            return result;
        }
        function deleteChapter_Click(MangaId,ChapterId) {
            var xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    alert("Đã xóa thành công!");
                    var trElement = document.getElementById('Chapter_' + ChapterId);// if only one id
                    if (trElement) {
                        trElement.remove();
                    }
                }
            };
            var strUrl = "/" + MangaId + "/Delete/" + ChapterId;
            xhttp.open("POST", strUrl, true);
            xhttp.send();
        }
    </script>
}